INSERT INTO `utilisateur` (`email`,`motdepasse`,`nom`,`solde`) VALUES ('un@test.com','1','un',1000);
INSERT INTO `utilisateur` (`email`,`motdepasse`,`nom`,`solde`) VALUES ('deux@test.com','2','deux',2000);
INSERT INTO `utilisateur` (`email`,`motdepasse`,`nom`,`solde`) VALUES ('trois@test.com','3','trois',3000);
INSERT INTO `utilisateur` (`email`,`motdepasse`,`nom`,`solde`) VALUES ('quatre@test.com','4','quatre',4000);
INSERT INTO `utilisateur` (`email`,`motdepasse`,`nom`,`solde`) VALUES ('cinq@test.com','5','cinq',5000);
INSERT INTO `creditbanque` (`idcredit`,`utilisateurcredit`,`comptebancaire`,`montant`,`date`) VALUES (1,'un@test.com','123456789',100,'2022-08-11 13:47:48');
INSERT INTO `creditbanque` (`idcredit`,`utilisateurcredit`,`comptebancaire`,`montant`,`date`) VALUES (2,'deux@test.com','123456789',200,'2022-08-11 13:47:08');
INSERT INTO `debitbanque` (`iddebit`,`utilisateurdebit`,`comptebancaire`,`montant`,`date`) VALUES (1,'un@test.com','123456789',10,'2022-08-11 13:54:40');
INSERT INTO `debitbanque` (`iddebit`,`utilisateurdebit`,`comptebancaire`,`montant`,`date`) VALUES (2,'deux@test.com','222222222',20,'2022-08-11 13:54:40');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (1,'un@test.com','deux@test.com',1,'2022-08-11 13:58:38','1€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (2,'un@test.com','deux@test.com',2,'2022-08-11 13:59:03','2€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (3,'un@test.com','deux@test.com',1,'2022-08-11 13:59:26','1€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (4,'un@test.com','deux@test.com',2,'2022-08-11 13:59:35','2€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (5,'un@test.com','deux@test.com',3,'2022-08-12 13:59:35','3€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (6,'un@test.com','deux@test.com',4,'2022-08-13 13:59:35','4€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (7,'un@test.com','deux@test.com',5,'2022-08-14 13:59:35','5€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (8,'un@test.com','deux@test.com',1,'2022-08-11 13:58:38','1€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (9,'un@test.com','deux@test.com',2,'2022-08-11 13:59:03','2€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (10,'un@test.com','deux@test.com',1,'2022-08-11 13:59:26','1€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (11,'un@test.com','deux@test.com',2,'2022-08-11 13:59:35','2€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (12,'un@test.com','deux@test.com',3,'2022-08-12 13:59:35','3€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (13,'un@test.com','deux@test.com',4,'2022-08-13 13:59:35','4€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (14,'un@test.com','deux@test.com',5,'2022-08-14 13:59:35','5€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (15,'un@test.com','deux@test.com',1,'2022-08-11 13:58:38','1€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (16,'un@test.com','deux@test.com',2,'2022-08-11 13:59:03','2€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (17,'un@test.com','deux@test.com',1,'2022-08-11 13:59:26','1€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (18,'un@test.com','deux@test.com',2,'2022-08-11 13:59:35','2€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (19,'un@test.com','deux@test.com',3,'2022-08-12 13:59:35','3€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (20,'un@test.com','deux@test.com',4,'2022-08-13 13:59:35','4€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (21,'un@test.com','deux@test.com',5,'2022-08-14 13:59:35','5€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (22,'un@test.com','deux@test.com',1,'2022-08-11 13:58:38','1€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (23,'un@test.com','deux@test.com',2,'2022-08-11 13:59:03','2€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (24,'un@test.com','deux@test.com',1,'2022-08-11 13:59:26','1€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (25,'un@test.com','deux@test.com',2,'2022-08-11 13:59:35','2€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (26,'un@test.com','deux@test.com',3,'2022-08-12 13:59:35','3€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (27,'un@test.com','deux@test.com',4,'2022-08-13 13:59:35','4€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (28,'un@test.com','deux@test.com',5,'2022-08-14 13:59:35','5€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (29,'un@test.com','deux@test.com',1,'2022-08-11 13:58:38','1€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (30,'un@test.com','deux@test.com',2,'2022-08-11 13:59:03','2€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (31,'un@test.com','deux@test.com',1,'2022-08-11 13:59:26','1€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (32,'un@test.com','deux@test.com',2,'2022-08-11 13:59:35','2€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (33,'un@test.com','deux@test.com',3,'2022-08-12 13:59:35','3€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (34,'un@test.com','deux@test.com',4,'2022-08-13 13:59:35','4€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (35,'un@test.com','deux@test.com',5,'2022-08-14 13:59:35','5€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (36,'un@test.com','deux@test.com',1,'2022-08-11 13:58:38','1€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (37,'un@test.com','deux@test.com',2,'2022-08-11 13:59:03','2€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (38,'un@test.com','deux@test.com',1,'2022-08-11 13:59:26','1€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (39,'un@test.com','deux@test.com',2,'2022-08-11 13:59:35','2€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (40,'un@test.com','deux@test.com',3,'2022-08-12 13:59:35','3€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (41,'un@test.com','deux@test.com',4,'2022-08-13 13:59:35','4€ de un vers deux');
INSERT INTO `transaction` (`idtransaction`,`utilisateurtransaction`,`utilisateurcontact`,`montant`,`date`,`description`) VALUES (42,'un@test.com','deux@test.com',5,'2022-08-14 13:59:35','5€ de un vers deux');
INSERT INTO `utilisateur_utilisateur` (`utilisateur_email`,`contact_email`) VALUES ('un@test.com','deux@test.com');
INSERT INTO `utilisateur_utilisateur` (`utilisateur_email`,`contact_email`) VALUES ('un@test.com','trois@test.com');
INSERT INTO `utilisateur_utilisateur` (`utilisateur_email`,`contact_email`) VALUES ('un@test.com','cinq@test.com');